// <auto-generated />
namespace Miniprojekt.Migrations.SentenceBuilding
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initzial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initzial));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151400561_Initzial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
