// <auto-generated />
namespace Miniprojekt.Text2Color
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Text2ColorInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Text2ColorInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201612131248415_Text2Color-Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
