// <auto-generated />
namespace Miniprojekt.Migrations.Text2Color
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NoMigrationActuallyNeeded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoMigrationActuallyNeeded));
        
        string IMigrationMetadata.Id
        {
            get { return "201612140740460_NoMigrationActuallyNeeded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
