namespace Miniprojekt.Migrations.Text2Color
{
    using Models.Text2Color;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Miniprojekt.DataAccess.Text2ColorContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            MigrationsDirectory = @"Migrations\Text2Color";
        }

        protected override void Seed(Miniprojekt.DataAccess.Text2ColorContext context)
        {
            // Update-Database -ConfigurationTypeName Miniprojekt.Migrations.Text2Color.Configuration
            context.Colors.AddOrUpdate(
                p => p.Name,
                  //new Color { Name = "Aliceblue", HexValue = "#f0f8ff" },
                  //new Color { Name = "Antiquewhite", HexValue = "#faebd7" },
                  //new Color { Name = "Aqua", HexValue = "#00ffff" },
                  //new Color { Name = "Aquamarine", HexValue = "#7fffd4" },
                  //new Color { Name = "Azure", HexValue = "#f0ffff" },
                  //new Color { Name = "Beige", HexValue = "#f5f5dc" },
                  //new Color { Name = "Bisque", HexValue = "#ffe4c4" },
                  new Color { Name = "Black", HexValue = "#000000" },
                  //new Color { Name = "Blanchedalmond", HexValue = "#ffebcd" },
                  //new Color { Name = "Blue", HexValue = "#0000ff" },
                  //new Color { Name = "Blueviolet", HexValue = "#8a2be2" },
                  new Color { Name = "Brown", HexValue = "#a52a2a" },
                  //new Color { Name = "Burlywood", HexValue = "#deb887" },
                  //new Color { Name = "Cadetblue", HexValue = "#5f9ea0" },
                  //new Color { Name = "Chartreuse", HexValue = "#7fff00" },
                  //new Color { Name = "Chocolate", HexValue = "#d2691e" },
                  //new Color { Name = "Coral", HexValue = "#ff7f50" },
                  //new Color { Name = "Cornflowerblue", HexValue = "#6495ed" },
                  //new Color { Name = "Cornsilk", HexValue = "#fff8dc" },
                  //new Color { Name = "Crimson", HexValue = "#dc143c" },
                  new Color { Name = "Cyan", HexValue = "#00ffff" },
                  new Color { Name = "Darkblue", HexValue = "#00008b" },
                  //new Color { Name = "Darkcyan", HexValue = "#008b8b" },
                  //new Color { Name = "Darkgoldenrod", HexValue = "#b8860b" },
                  //new Color { Name = "Darkgray", HexValue = "#a9a9a9" },
                  //new Color { Name = "Darkgreen", HexValue = "#006400" },
                  //new Color { Name = "Darkgrey", HexValue = "#a9a9a9" },
                  //new Color { Name = "Darkkhaki", HexValue = "#bdb76b" },
                  //new Color { Name = "Darkmagenta", HexValue = "#8b008b" },
                  //new Color { Name = "Darkolivegreen", HexValue = "#556b2f" },
                  //new Color { Name = "Darkorange", HexValue = "#ff8c00" },
                  //new Color { Name = "Darkorchid", HexValue = "#9932cc" },
                  //new Color { Name = "Darkred", HexValue = "#8b0000" },
                  //new Color { Name = "Darksalmon", HexValue = "#e9967a" },
                  //new Color { Name = "Darkseagreen", HexValue = "#8fbc8f" },
                  //new Color { Name = "Darkslateblue", HexValue = "#483d8b" },
                  //new Color { Name = "Darkslategray", HexValue = "#2f4f4f" },
                  //new Color { Name = "Darkslategrey", HexValue = "#2f4f4f" },
                  //new Color { Name = "Darkturquoise", HexValue = "#00ced1" },
                  //new Color { Name = "Darkviolet", HexValue = "#9400d3" },
                  //new Color { Name = "Deeppink", HexValue = "#ff1493" },
                  //new Color { Name = "Deepskyblue", HexValue = "#00bfff" },
                  //new Color { Name = "Dimgray", HexValue = "#696969" },
                  //new Color { Name = "Dimgrey", HexValue = "#696969" },
                  //new Color { Name = "Dodgerblue", HexValue = "#1e90ff" },
                  //new Color { Name = "Firebrick", HexValue = "#b22222" },
                  //new Color { Name = "Floralwhite", HexValue = "#fffaf0" },
                  //new Color { Name = "Forestgreen", HexValue = "#228b22" },
                  //new Color { Name = "Fuchsia", HexValue = "#ff00ff" },
                  //new Color { Name = "Gainsboro", HexValue = "#dcdcdc" },
                  //new Color { Name = "Ghostwhite", HexValue = "#f8f8ff" },
                  //new Color { Name = "Gold", HexValue = "#ffd700" },
                  //new Color { Name = "Goldenrod", HexValue = "#daa520" },
                  new Color { Name = "Gray", HexValue = "#808080" },
                  new Color { Name = "Green", HexValue = "#008000" },
                  //new Color { Name = "Greenyellow", HexValue = "#adff2f" },
                  //new Color { Name = "Honeydew", HexValue = "#f0fff0" },
                  //new Color { Name = "Hotpink", HexValue = "#ff69b4" },
                  //new Color { Name = "Indianred", HexValue = "#cd5c5c" },
                  //new Color { Name = "Indigo", HexValue = "#4b0082" },
                  //new Color { Name = "Ivory", HexValue = "#fffff0" },
                  //new Color { Name = "Khaki", HexValue = "#f0e68c" },
                  //new Color { Name = "Lavender", HexValue = "#e6e6fa" },
                  //new Color { Name = "Lavenderblush", HexValue = "#fff0f5" },
                  //new Color { Name = "Lawngreen", HexValue = "#7cfc00" },
                  //new Color { Name = "Lemonchiffon", HexValue = "#fffacd" },
                  new Color { Name = "Lightblue", HexValue = "#add8e6" },
                  //new Color { Name = "Lightcoral", HexValue = "#f08080" },
                  //new Color { Name = "Lightcyan", HexValue = "#e0ffff" },
                  //new Color { Name = "Lightgoldenrodyellow", HexValue = "#fafad2" },
                  //new Color { Name = "Lightgray", HexValue = "#d3d3d3" },
                  //new Color { Name = "Lightgreen", HexValue = "#90ee90" },
                  //new Color { Name = "Lightpink", HexValue = "#ffb6c1" },
                  //new Color { Name = "Lightsalmon", HexValue = "#ffa07a" },
                  //new Color { Name = "Lightseagreen", HexValue = "#20b2aa" },
                  //new Color { Name = "Lightskyblue", HexValue = "#87cefa" },
                  //new Color { Name = "Lightslategray", HexValue = "#778899" },
                  //new Color { Name = "Lightslategrey", HexValue = "#778899" },
                  //new Color { Name = "Lightsteelblue", HexValue = "#b0c4de" },
                  //new Color { Name = "Lightyellow", HexValue = "#ffffe0" },
                  new Color { Name = "Lime", HexValue = "#00ff00" },
                  //new Color { Name = "Limegreen", HexValue = "#32cd32" },
                  //new Color { Name = "Linen", HexValue = "#faf0e6" },
                  new Color { Name = "Magenta", HexValue = "#ff00ff" },
                  //new Color { Name = "Maroon", HexValue = "#800000" },
                  //new Color { Name = "Mediumaquamarine", HexValue = "#66cdaa" },
                  //new Color { Name = "Mediumblue", HexValue = "#0000cd" },
                  //new Color { Name = "Mediumorchid", HexValue = "#ba55d3" },
                  //new Color { Name = "Mediumpurple", HexValue = "#9370db" },
                  //new Color { Name = "Mediumseagreen", HexValue = "#3cb371" },
                  //new Color { Name = "Mediumslateblue", HexValue = "#7b68ee" },
                  //new Color { Name = "Mediumspringgreen", HexValue = "#00fa9a" },
                  //new Color { Name = "Mediumturquoise", HexValue = "#48d1cc" },
                  //new Color { Name = "Mediumvioletred", HexValue = "#c71585" },
                  //new Color { Name = "Midnightblue", HexValue = "#191970" },
                  //new Color { Name = "Mintcream", HexValue = "#f5fffa" },
                  //new Color { Name = "Mistyrose", HexValue = "#ffe4e1" },
                  //new Color { Name = "Moccasin", HexValue = "#ffe4b5" },
                  //new Color { Name = "Navajowhite", HexValue = "#ffdead" },
                  //new Color { Name = "Navy", HexValue = "#000080" },
                  //new Color { Name = "Oldlace", HexValue = "#fdf5e6" },
                  //new Color { Name = "Olive", HexValue = "#808000" },
                  //new Color { Name = "Olivedrab", HexValue = "#6b8e23" },
                  //new Color { Name = "Orange", HexValue = "#ffa500" },
                  //new Color { Name = "Orangered", HexValue = "#ff4500" },
                  //new Color { Name = "Orchid", HexValue = "#da70d6" },
                  //new Color { Name = "Palegoldenrod", HexValue = "#eee8aa" },
                  new Color { Name = "Palegreen", HexValue = "#98fb98" },
                  //new Color { Name = "Paleturquoise", HexValue = "#afeeee" },
                  //new Color { Name = "Palevioletred", HexValue = "#db7093" },
                  //new Color { Name = "Papayawhip", HexValue = "#ffefd5" },
                  //new Color { Name = "Peachpuff", HexValue = "#ffdab9" },
                  //new Color { Name = "Peru", HexValue = "#cd853f" },
                  new Color { Name = "Pink", HexValue = "#ffc0cb" },
                  //new Color { Name = "Plum", HexValue = "#dda0dd" },
                  //new Color { Name = "Powderblue", HexValue = "#b0e0e6" },
                  new Color { Name = "Purple", HexValue = "#800080" },
                  //new Color { Name = "Rebeccapurple", HexValue = "#663399" },
                  new Color { Name = "Red", HexValue = "#ff0000" },
                  //new Color { Name = "Rosybrown", HexValue = "#bc8f8f" },
                  //new Color { Name = "Royalblue", HexValue = "#4169e1" },
                  //new Color { Name = "Saddlebrown", HexValue = "#8b4513" },
                  //new Color { Name = "Salmon", HexValue = "#fa8072" },
                  //new Color { Name = "Sandybrown", HexValue = "#f4a460" },
                  //new Color { Name = "Seagreen", HexValue = "#2e8b57" },
                  //new Color { Name = "Seashell", HexValue = "#fff5ee" },
                  //new Color { Name = "Sienna", HexValue = "#a0522d" },
                  //new Color { Name = "Silver", HexValue = "#c0c0c0" },
                  //new Color { Name = "Skyblue", HexValue = "#87ceeb" },
                  //new Color { Name = "Slateblue", HexValue = "#6a5acd" },
                  //new Color { Name = "Slategray", HexValue = "#708090" },
                  //new Color { Name = "Slategrey", HexValue = "#708090" },
                  //new Color { Name = "Snow", HexValue = "#fffafa" },
                  //new Color { Name = "Springgreen", HexValue = "#00ff7f" },
                  //new Color { Name = "Steelblue", HexValue = "#4682b4" },
                  //new Color { Name = "Tan", HexValue = "#d2b48c" },
                  new Color { Name = "Teal", HexValue = "#008080" },
                  //new Color { Name = "Thistle", HexValue = "#d8bfd8" },
                  //new Color { Name = "Tomato", HexValue = "#ff6347" },
                  //new Color { Name = "Turquoise", HexValue = "#40e0d0" },
                  new Color { Name = "Violet", HexValue = "#ee82ee" },
                  //new Color { Name = "Wheat", HexValue = "#f5deb3" },
                  new Color { Name = "White", HexValue = "#ffffff" },
                  //new Color { Name = "Whitesmoke", HexValue = "#f5f5f5" },
                  new Color { Name = "Yellow", HexValue = "#ffff00" }
                  //new Color { Name = "Yellowgreen", HexValue = "#9acd32" }
            );
        }
    }
}
